*** Variables ***
${Codelist_Extensions_members}    ${DATAFOLDER}${/}Codelist_with_def_hierarchy_extensions_and_members.xlsx
${Code_list_with_30_Codes}    ${DATAFOLDER}${/}Code_list_with_30_Codes.xlsx
${Extension_calculation_hierarchy}    ${DATAFOLDER}${/}Extension_calculation_hierarchy.xlsx
${Extension_definition_hierarchy}    ${DATAFOLDER}${/}Extension_definition_hierarchy.xlsx
${Calculation_hierarchy_members}    ${DATAFOLDER}${/}Calculation_hierarchy_members.xlsx
${Definition_hierarchy_members}    ${DATAFOLDER}${/}Definition_hierarchy_members.xlsx
${Extensions_without_codeschemes_value}    ${DATAFOLDER}${/}Extensions_without_codeschemes_value.xlsx
${Extensions_invalid_code_in_members_sheet}    ${DATAFOLDER}${/}Extensions_invalid_code_in_members_sheet.xlsx
${Extensios_max_hierarchy_level}    ${DATAFOLDER}${/}Extensions_max_hierarchy_level.xlsx
${Extensios_max_hierarchy_level}    ${DATAFOLDER}${/}Extensions_max_hierarchy_level.xlsx
${Extension_Scheme_calculation_hierarchy}    ${DATAFOLDER}${/}Extension_Scheme_calculation_hierarchy.xlsx
${Unaryoperator_value_missing}    ${DATAFOLDER}${/}Calculation_hierarchy_members_unaryoperator_value_missing.xlsx
${Extensions_no_extensionvalue_column}    ${DATAFOLDER}${/}Extensions_no_extensionvalue_column.xlsx
${Code_list_with_30_Codes_valid}    ${DATAFOLDER}${/}Code_list_with_30_Codes_valid.xlsx
${Extensions_new_version_creation}    ${DATAFOLDER}${/}Extensions_and_members_for_new_version_creation.xlsx
${Invalid_unaryoperator_value}    ${DATAFOLDER}${/}Calculation_members_invalid_unary_operator.xlsx
${Code_list_extensions_broader_members}    ${DATAFOLDER}${/}Codelist_with_codes_extensions_and_broader_members.xlsx
${Modify_dpm_metric}    ${DATAFOLDER}${/}Modify_dpm_metric.xlsx
${2_dpms_should_fail}    ${DATAFOLDER}${/}Modify_dpm_metric_2_dpms_should_fail.xlsx
${Modify_DPM_explicit_domain}    ${DATAFOLDER}${/}Modify_DPM_explicit_domain_extension.xlsx
${Code_list_codes_DPM_Dimension_extension}    ${DATAFOLDER}${/}Code_list_codes_DPM_Dimension_extension.xlsx
${Code_list_codes_DPM_extension_all}    ${DATAFOLDER}${/}Code_list_codes_DPM_all.xlsx
${DPM_extension_relations_to_other_members}    ${DATAFOLDER}${/}DPM_extensions_relations_to_other_members.xlsx
${Code_list_for_cross_reference_list_creation}    ${DATAFOLDER}${/}Code_list_and_codes_for_cross_reference_list.xlsx
${Code_list_with_links_and_default_code}    ${DATAFOLDER}${/}Code_list_with_links_and_default_code.xlsx
${Code_list_with_cross_reference_list}    ${DATAFOLDER}${/}Code_list_with_cross_reference_list.xlsx
${filter_1_Code_list_three_extensions}    ${DATAFOLDER}${/}filter_1_Code_list_three_extensions.xlsx
${filter_2_Code_list_one_extension}    ${DATAFOLDER}${/}filter_2_Code_list_one_extension.xlsx
${Code_list_with_calculation_hierarchy_members}    ${DATAFOLDER}${/}Code_list_calc_hier_members.xlsx
${Code_list_with_definition_hierarchy_members}    ${DATAFOLDER}${/}Code_list_with_def_hierarchy_extension_and_members.xlsx
${Code_list_with_duplicate_member_id_values}    ${DATAFOLDER}${/}Update_code_list_with_duplicate_member_id_values.xlsx
${Code_list_with_DPM_Metric_extension}    ${DATAFOLDER}${/}Code_list_with_DPM_Metric_extension.xlsx
${Code_list_DPM_Metric_Credit}    ${DATAFOLDER}${/}DPM_Metric_Credit.xlsx
${Code_list_DPM_Metric_Credit_no_member_id}    ${DATAFOLDER}${/}DPM_Metric_Credit_no_member_id.xlsx
${Code_list_with_update_members}    ${DATAFOLDER}${/}Code_list_with_update_members.xlsx
${Update_members_invalid_relation}    ${DATAFOLDER}${/}Update_members_invalid_relation.xlsx
${code_list_extensions_100_members}    ${DATAFOLDER}${/}Code_list_with_extensions_and_100_members.xlsx
${Code_list_with_multiple_extensions}    ${DATAFOLDER}${/}filter_Code_list_with_multiple_extensions.xlsx
${Code_list_codes_DPM_all_invalid_propertytype}    ${DATAFOLDER}${/}Code_list_codes_DPM_all_invalid_propertytype.xlsx
${Code_list_codes_DPM_all_no_values}    ${DATAFOLDER}${/}Code_list_codes_DPM_all_no_values.xlsx
${Code_list_with_extensions_and_member_relations}    ${DATAFOLDER}${/}Code_list_with_extensions_and_member_relations.xlsx

#Excel paths
${testiautomaatiokoodisto_with_code}    ${DATAFOLDER}${/}testiautomaatiokoodisto_with_code.xlsx
${testiautomaatiokoodisto2_with_code}    ${DATAFOLDER}${/}testiautomaatiokoodisto2_with_code.xlsx
${testiautomaatiokoodisto1_with_codes}    ${DATAFOLDER}${/}testiautomaatiokoodisto1_with_codes.xlsx
${Testikoodisto_T200}    ${DATAFOLDER}${/}Testikoodisto_T200.xlsx
${Code_filter}    ${DATAFOLDER}${/}Code_filter.xlsx
${Code_list_Codes_new_version}    ${DATAFOLDER}${/}Code_list_and_codes_for_new_version_creation.xlsx
${Code_list_with_feedback_column}    ${DATAFOLDER}${/}Code_list_with_feedback_column.xlsx
${Code_list_test_dcat}    ${DATAFOLDER}${/}Code_list_testi_dcat.xlsx
${Code_list_codes_with_languages}    ${DATAFOLDER}${/}Code_list_codes_with_languages.xlsx
${Code_list_codes_with_languages_empty}    ${DATAFOLDER}${/}Code_list_codes_with_languages_empty.xlsx
${Update_codes_with_languages}    ${DATAFOLDER}${/}Update_codes_with_languages.xlsx
${Code_list_with_30_Codes}    ${DATAFOLDER}${/}Code_list_with_30_Codes.xlsx
${Code_list_with_30_Codes_valid}    ${DATAFOLDER}${/}Code_list_with_30_Codes_valid.xlsx
${Code_list_with_30_Codes_status_with_space}    ${DATAFOLDER}${/}Code_list_with_30_Codes_status_with_space.xlsx
${Codes_status_with_space}    ${DATAFOLDER}${/}Codes_status_with_space.xlsx
${Code_list_with_30_codes_and_instructions_link}    ${DATAFOLDER}${/}Code_list_with_30_codes_and_instructions_link.xlsx
${Code_links_with_space}    ${DATAFOLDER}${/}Code_links_with_space.xlsx
${Code_list_with_30_codes_incomplete}    ${DATAFOLDER}${/}Code_list_with_30_codes_incomplete.xlsx
${Codes_with_order}    ${DATAFOLDER}${/}Codes_with_order.xlsx
${Codes_list_with_languages}    ${DATAFOLDER}${/}Code_list_with_languages.xlsx
${Codes_list_and_extension_with_languages}    ${DATAFOLDER}${/}Code_list_codes_extensions_and_members_with_languages.xlsx
${Code_list_with_same_preflabel_values}    ${DATAFOLDER}${/}Code_list_with_same_preflabel_values.xlsx
${Codes_with_same_preflabel_and_definition_value}    ${DATAFOLDER}${/}Codes_with_same_preflabel_and_definition_value.xlsx

#Excel paths
${Code_list_no_codeValue}    ${DATAFOLDER}${/}Code_list_no_codeValue.xlsx
${Code_list_no_classification}    ${DATAFOLDER}${/}Code_list_no_classification_value.xlsx
${Code_list_invalid_classification}    ${DATAFOLDER}${/}Code_list_incorrect_classification_value.xlsx
${Code_list_no_status_value}    ${DATAFOLDER}${/}Code_list_no_status_value.xlsx
${Code_list_invalid_status_value}    ${DATAFOLDER}${/}Code_list_incorrect_status_value.xlsx
${Code_list_with_duplicate_columns}    ${DATAFOLDER}${/}Code_list_with_multiple_columns.xlsx
${Duplicate_code_lists}    ${DATAFOLDER}${/}Duplicate_code_lists.xlsx
${Code_list_exists}    ${DATAFOLDER}${/}Code_list_exists.xlsx
${Code_list_invalid_codeValue}    ${DATAFOLDER}${/}Code_list_with_invalid_codevalue.xlsx
${Code_list_max_hierarchy_level_codes}    ${DATAFOLDER}${/}Code_list_and_codes_with_max_hierarchy_level.xlsx
${2x_code_list}    ${DATAFOLDER}${/}2x_codelists.xlsx
${Code_list_invalid_propertytype}    ${DATAFOLDER}${/}Code_list_with_links_invalid_propertytype.xlsx
${Code_list_invalid_enddate}    ${DATAFOLDER}${/}Code_list_with_links_invalid_endate.xlsx
${Same_sub_code_list}    ${DATAFOLDER}${/}same_sub_code_list.xlsx
${Unknown_sub_code_list}    ${DATAFOLDER}${/}unknown_sub_code_list.xlsx
${empty_file}          ${DATAFOLDER}${/}empty.xlsx
${No_content_excel}    ${DATAFOLDER}${/}No_content_excel.xlsx
${Code_list_with_invalid_link_urls}    ${DATAFOLDER}${/}Code_list_with_invalid_link_URLs.xlsx
${Code_list_invalid_delimiter_in_language_code}    ${DATAFOLDER}${/}Code_list_invalid_delimiter_in_language_code.xlsx

${Codes_codevalue_missing}    ${DATAFOLDER}${/}Codes_codevalue_missing.xlsx
${Codes_status_missing}    ${DATAFOLDER}${/}Codes_status_missing.xlsx
${Codes_with_invalid_status}    ${DATAFOLDER}${/}Codes_with_invalid_status.xlsx
${Codes_with_invalid_broader}    ${DATAFOLDER}${/}Codes_with_invalid_broader_value.xlsx
${Codes_with_same_broader}    ${DATAFOLDER}${/}Codes_with_same_broader_value.xlsx
${Codes_with_duplicate_columns}    ${DATAFOLDER}${/}Codes_with_duplicate_columns.xlsx
${Codes_with_invalid_HL}    ${DATAFOLDER}${/}Codes_with_invalid_HL_value.xlsx
${Codes_without_codevalue_column}    ${DATAFOLDER}${/}Codes_without_codevalue_column.xlsx
${Codes_with_invalid_startdate}    ${DATAFOLDER}${/}Codes_with_invalid_startdate.xlsx
${Codes_with_invalid_ID}    ${DATAFOLDER}${/}Codes_with_invalid_ID.xlsx
${Update_Code_valid_draft}    ${DATAFOLDER}${/}Update_code_valid_draft.xlsx
${Duplicate_Codes}    ${DATAFOLDER}${/}Duplicate_codes.xlsx
${Codes_without_ID_column}    ${DATAFOLDER}${/}Codes_without_ID_column.xlsx
${Codes_invalid_codevalue}    ${DATAFOLDER}${/}Codes_invalid_codevalue.xlsx
${Codes_with_missing_order_value}    ${DATAFOLDER}${/}Codes_with_missing_order.xlsx
${Same_order_values}    ${DATAFOLDER}${/}Codes_with_same_order_values.xlsx
${Codes_with_order_values}    ${DATAFOLDER}${/}Codes_with_order_values.xlsx
${Codes_with_existing_order_values}    ${DATAFOLDER}${/}Codes_with_existing_order_values.xlsx
${Codes_with_invalid_order_values}    ${DATAFOLDER}${/}Codes_with_invalid_order_values.xlsx
${empty_file}          ${DATAFOLDER}${/}empty.xlsx
${No_content_excel}    ${DATAFOLDER}${/}No_content_excel.xlsx

${Code_list_without_codes}    ${DATAFOLDER}${/}Draft_Code_list_without_codes.xlsx
${Code_list_with_codes}    ${DATAFOLDER}${/}Valid_Code_list_with_codes.xlsx
${Draft_Codes_with_broader}    ${DATAFOLDER}${/}Codes_500_broader.xlsx
${Update_Codes}    ${DATAFOLDER}${/}Update_Codes.xlsx
${Multiple_codelists_and_codes}    ${DATAFOLDER}${/}Multiple_codelists_and_codes.xlsx
${Codelist_ExtensionSchemes}    ${DATAFOLDER}${/}Codelist_with_ExtensionSchemes.xlsx
${Codelist_with_defaultcode}    ${DATAFOLDER}${/}Codelist_with_defaultcode.xlsx
${Variant_code_list}    ${DATAFOLDER}${/}Variant_code_list_and_codes.xlsx
${Code_list_Codes_new_version}    ${DATAFOLDER}${/}Code_list_and_codes_for_new_version_creation.xlsx
${Code_list_with_languagecode}    ${DATAFOLDER}${/}Code_list_with_languagecodes.xlsx
${Code_list_with_30_Codes}    ${DATAFOLDER}${/}Code_list_with_30_Codes.xlsx
${Code_list_version2}    ${DATAFOLDER}${/}Code_list_version2.xlsx
${Code_list_version3}    ${DATAFOLDER}${/}Code_list_version3.xlsx
${Variant_no_end_date}    ${DATAFOLDER}${/}Variant_code_list_and_codes_no_end_date.xlsx
${Code_list_with_links}    ${DATAFOLDER}${/}Code_list_with_links.xlsx
${Code_list_with_sub_code_list_in_code}    ${DATAFOLDER}${/}Code_list_with_sub_code_list_in_code.xlsx
${Code_list_with_default_code_new_version}    ${DATAFOLDER}${/}Code_list_codes_default_code_for_new_version_valid.xlsx
${Code_list_with_30_Codes_updated}    ${DATAFOLDER}${/}Code_list_with_30_Codes_updated.xlsx
${Code_list_with_30_Codes_invalid_codevalue}    ${DATAFOLDER}${/}Code_list_with_30_Codes_invalid_codevalue.xlsx
${Codelist_special_characters_for_codes}    ${DATAFOLDER}${/}Codelist_special_characters_for_codes.xlsx